USER = byorgey
PASS = a0303017

html:
	BlogLiterately -t http://byorgey.wordpress.com/xmlrpc.php $(USER) $(PASS) $(TITLE) $(FILE).lhs > $(FILE).html

initial:
	BlogLiterately http://byorgey.wordpress.com/xmlrpc.php $(USER) $(PASS) $(TITLE) $(FILE).lhs

preview:
	BlogLiterately --postid=$(ID) http://byorgey.wordpress.com/xmlrpc.php $(USER) $(PASS) $(TITLE) $(FILE).lhs

publish:
	BlogLiterately --publish --postid=$(ID) http://byorgey.wordpress.com/xmlrpc.php $(USER) $(PASS) $(TITLE) $(FILE).lhs
